library(GetoptLong)

base_dir = "/omics/groups/OE0246/internal/guz/cola_hc/examples"

setwd(base_dir)

## these functions can not be used in parallel, so here I first save the data object in each folder
data = BaronPancreasData('mouse'); saveRDS(data, file = "BaronPancreas_mouse/BaronPancreas_mouse_data.rds")
data = BuettnerESCData(); saveRDS(data, file = "BuettnerESC/BuettnerESC_data.rds")
data = DarmanisBrainData(); saveRDS(data, file = "DarmanisBrain/DarmanisBrain_data.rds")
data = GrunHSCData(); saveRDS(data, file = "GrunHSC/GrunHSC_data.rds")
data = GrunPancreasData(); saveRDS(data, file = "GrunPancreas/GrunPancreas_data.rds")
data = KolodziejczykESCData(); saveRDS(data, file = "KolodziejczykESC/KolodziejczykESC_data.rds")
data = LaMannoBrainData('human-es'); saveRDS(data, file = "LaMannoBrain_human_es/LaMannoBrain_human_es_data.rds")
data = LaMannoBrainData('human-embryo'); saveRDS(data, file = "LaMannoBrain_human_embryo/LaMannoBrain_human_embryo_data.rds")
data = LaMannoBrainData('human-ips'); saveRDS(data, file = "LaMannoBrain_human_ips/LaMannoBrain_human_ips_data.rds")
data = LaMannoBrainData('mouse-adult'); saveRDS(data, file = "LaMannoBrain_mouse_adult/LaMannoBrain_mouse_adult_data.rds")
data = LaMannoBrainData('mouse-embryo'); saveRDS(data, file = "LaMannoBrain_mouse_embryo/LaMannoBrain_mouse_embryo_data.rds")
data = LawlorPancreasData(); saveRDS(data, file = "LawlorPancreas/LawlorPancreas_data.rds")
data = LengESCData(); saveRDS(data, file = "LengESC/LengESC_data.rds")
data = ReprocessedTh2Data(); saveRDS(data, file = "ReprocessedTh2/ReprocessedTh2_data.rds")
data = MessmerESCData(); saveRDS(data, file = "MessmerESC/MessmerESC_data.rds")
data = MuraroPancreasData(); saveRDS(data, file = "MuraroPancreas/MuraroPancreas_data.rds")
data = NestorowaHSCData(); saveRDS(data, file = "NestorowaHSC/NestorowaHSC_data.rds")
data = PollenGliaData(); saveRDS(data, file = "PollenGlia/PollenGlia_data.rds")
data = RichardTCellData(); saveRDS(data, file = "RichardTCell/RichardTCell_data.rds")
data = RomanovBrainData(); saveRDS(data, file = "RomanovBrain/RomanovBrain_data.rds")
data = SegerstolpePancreasData(); saveRDS(data, file = "SegerstolpePancreas/SegerstolpePancreas_data.rds")
data = TasicBrainData(); saveRDS(data, file = "TasicBrain/TasicBrain_data.rds")
data = ReprocessedAllenData(); saveRDS(data, file = "ReprocessedAllen/ReprocessedAllen_data.rds")
data = XinPancreasData(); saveRDS(data, file = "XinPancreas/XinPancreas_data.rds")
data = ZeiselBrainData(); saveRDS(data, file = "ZeiselBrain/ZeiselBrain_data.rds")
data = ReprocessedFluidigmData(); saveRDS(data, file = "Fluidigm/Fluidigm_data.rds")


lines = readLines("/omics/groups/OE0246/internal/guz/cola_hc/script/examples.R")

lines = lines[!grepl("^#\\s", lines)]

ind = which(grepl("^#{4,}", lines))
ind2 = c(ind[-1] - 1, length(lines))

examples = list()

process_counts = '
process_counts = function(data, column = NULL) {
    mat = assays(data)$counts
    mat = as.matrix(mat)
    s = colSums(mat)
    fa = s/mean(s)
    for(i in 1:ncol(mat)) mat[, i]/fa[i]
    mat = adjust_matrix(log2(mat + 1))

    anno = NULL
    if(!is.null(column)) {
    	anno = colData(data)
   		anno = as.data.frame(anno)
        anno = anno[, column, drop = FALSE]
    }

    list(mat = mat, anno = anno)
}
'

for(i in seq_along(ind)) {

	code = lines[seq(ind[i]+1, ind2[i])]

	if(any(grepl("[A-Z]\\w+Data\\(", code))) {
		if(!any(grepl("library\\(scRNAseq\\)", code))) {
			code = c("library(scRNAseq)", code)
		}
	}

	if(any(grep("process_counts", code))) {
		code = c(process_counts, code)
	}

	if(!any(grepl("library\\(cola\\)", code))) {
		code = c("library(cola)", code)
	}

	name = gsub("[# ]", "", lines[ind[i]])
	
	if(!any(grepl("setwd", code))) {
		code = c(qq("setwd(\"@{base_dir}/@{name}\")"), code)
	}

	code = gsub("\\t", "    ", code)

	if(!any(grepl("cola_report", code))) {
		code= c(code, qq("cola_report(rh, output = \"@{name}_cola_rh_report\", title = \"cola Report for Hierarchical Partitioning - '@{name}'\")"))
	}

	examples[[i]] = list(name = name, code = code)
}


## generate an Rscript and a markdown under each folder

as_markdown = function(example) {
	name = example$name
	code = example$code
	code = code[!grepl("setwd", code)]
	code = paste(code, collapse = "\n")
	code = gsub("\\s*$", "\n", code)

	qq("
## Hierarchical consensus partitioning analysis on dataset '@{name}'

Runnable code:

```r
@{code}```

[The HTML report is here.](https://cola-rh.github.io/@{name}/@{name}_cola_rh_report/cola_hc.html) (generated by __cola__ version 2.0.0, R 4.1.0.)
")

}


for(i in seq_along(examples)) {
	name = examples[[i]]$name
	if(name == "") next

	dir.create(qq("@{base_dir}/@{name}/"), showWarnings = FALSE)
	
	writeLines(as_markdown(examples[[i]]), con = qq("@{base_dir}/@{name}/index.md"))

	code = examples[[i]]$code
		
	if(any(grepl("[A-Z]\\w+Data\\(", code))) {
		i = which(grepl("[A-Z]\\w+Data\\(", code))
		code[i] = qq("data = readRDS('@{base_dir}/@{name}/@{name}_data.rds')")
		writeLines(code, con = qq("@{base_dir}/@{name}/@{name}_cola_rh.R"))
	} else {
		writeLines(examples[[i]]$code, con = qq("@{base_dir}/@{name}/@{name}_cola_rh.R"))
	}
}


## submit jobs
library(bsub)
for(i in seq_along(examples)) {
	name = examples[[i]]$name
	if(name == "") next

	bsub_script(qq("@{base_dir}/@{name}/@{name}_cola_rh.R"), name = qq("cola_rh_@{name}"), hour = 20, memory = 60, core = 4, enforce = F)
}

############## host on github ################
library(GetoptLong)
library(gh)

username = "cola-rh"
token = 

delete_repo = function(repo, dir, where = c("remote", "local")) {
	qqcat("delete repo @{repo}\n")
	if("remote" %in% where) {
		gh("DELETE /repos/:owner/:repo", owner = username, repo = repo, .token = token)
	}

	if("local" %in% where) {
		owd = getwd()
		on.exit(setwd(owd))
		setwd(dir)
		if(file.exists(".git")) {
			unlink(".git", recursive = TRUE, force = TRUE)
		}
	}
}

create_repo = function(repo, dir, ignore = c("rds", "rds/", "Rplots.pdf", ".RData*"),
	where = c("remote", "local")) {
	
	all_repos = gh(qq("GET /users/@{username}/repos"))
	all_repos = vapply(all_repos, "[[", "", "name")
	if(repo %in% all_repos) {
		delete_repo(repo, dir)
	} else {
		delete_repo(repo, dir, where = "local")
	}

	qqcat("creating repo for @{repo}\n")
	if("remote" %in% where) {
		new_repo = gh("POST /user/repos", name = repo, owner = username, .token = token)
	}

	if("local" %in% where) {
		owd = getwd()
		on.exit(setwd(owd))
		setwd(dir)

		all_files = list.files()
		fs = file.size(all_files)
		large_files = all_files[fs > 1024*1024]
		cat(c(ignore, large_files), sep = "\n", file = ".gitignore")
		

		system("git init")
		system("git add .gitignore")
		system("git commit -m 'add .gitignore'")

		# if(!file.exists("readme.md")) {
		# 	qqcat("figures for @{repo}", file = "readme.md")
		# 	system("git add readme.md")
		# 	system("git commit -m 'add readme.md'")
		# }

		branch = system("git branch", intern = TRUE)
		if(!any(grepl("gh-pages", branch))) {
			system("git branch gh-pages")
		}
	}
}

update_repo = function(repo, dir) {
	qqcat("------------ upload for @{repo} -------------\n")

	owd = getwd()
	on.exit(setwd(owd))
	setwd(dir)

	system("git add --all")
	system(qq("git commit -m 'add files for @{repo}'"))
	system(qq("git push https://@{username}:@{token}@github.com/@{username}/@{repo}.git master"))
	system("git checkout gh-pages")
	system("git merge master")
	system(qq("git push https://@{username}:@{token}@github.com/@{username}/@{repo}.git gh-pages"))
	system("git checkout master")
}

sub_dirs = function(dir, pattern = NULL) {
	owd = getwd()
	on.exit(setwd(owd))
	setwd(dir)

	files = list.files(pattern = pattern)
	files[file.info(files)$isdir]
}

dir = sub_dirs(base_dir)

for(repo in dir[61:66]) {
	create_repo(repo, qq("@{base_dir}/@{repo}"))
}

##### push
for(repo in dir) {
	update_repo(repo, qq("@{base_dir}/@{repo}"))
}

